### ISSUE TITLE
"Could not retrieve geolocation data. Please try again later." error.

### ISSUE THREAD

**Issue by Depresst0** [koreesmith/thelounge-plugin-weather#5]
it happens when I type my City or Zip Code

**Comment by koreesmith** [comment]
Have you put in your own key for openweathermaps?

**Comment by koreesmith** [comment]
> it happens when I type my City or Zip Code

Please make sure to update the plugin with your own API key.  The place in the code to do that is here:

// Replace 'YOUR_API_KEY' with your actual OpenWeatherMap API key
const API_KEY = 'YOUR_API_KEY';

You can sign up for a free key here:  https://openweathermap.org
